### PR TITLE
Basic page structure

### PR DESCRIPTION
**Pull request by cynthiainga**
In this part of my project I:

- Create an npm project with webpack
- Write plain HTML markup with minimum styling
- Use ES6 modules, I import my `style.css` file in the index.js file

### CODE REVIEW

**Review by elmar8287 — APPROVED** [review]
Hi, @cynthiainga.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

## Please, consider my OPTIONAL suggestions before merging.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cynthiainga** [comment]
Thanks
But where is the optional suggestion?!

**Comment by elmar8287** [comment]
> Thanks But where is the optional suggestion?!

Dear @cynthiainga, sorry for it, maybe there is a technical issue. My comment was about the `.gitignore` file. I got in your commit history, that you added `node_modules` only on commit [Setup linters](https://github.com/cynthiainga/leaderboard/pull/1/commits/40d29ccf5c0a69334f3fc36dfc8ca599fd1b0ef1), which mean that your node_module folder was already in repo from the first commits - the node_modules make reviewing your project very slow, because of a big amount files. So, please, consider adding it into `.gitignore` in advance. I am at your disposal for any additional questions 👍 
Screen Shot 2022-03-01 at 23 55 45

**Comment by cynthiainga** [comment]
Ohh thanks, I will add it in my `.gitignore` file.

**Pull request merged**
